exports.NamePattern = require('./name.pattern')
exports.ImportPattern = require('./import.pattern')
exports.ExportPattern = require('./export.pattern')
exports.DepsPattern = require('./deps.pattern')
exports.WrapPattern = require('./wrapper.pattern')